version: '3.8' # 파일 포멧 버전: swarm과 호환, replicas 지원 (2020년)

services:
  postgres:
    image: postgres:17
    container_name: postgres17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: flix
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: