FROM openjdk:21-jdk-slim

COPY *.jar /app/myapp.jar

# JMX 및 RMI 관련 환경 변수 설정
ENTRYPOINT ["java", "-Dcom.sun.management.jmxremote", \
                   "-Dcom.sun.management.jmxremote.port=9010", \
                   "-Dcom.sun.management.jmxremote.rmi.port=9010", \
                   "-Dcom.sun.management.jmxremote.authenticate=false", \
                   "-Dcom.sun.management.jmxremote.ssl=false", \
                   "-Djava.rmi.server.hostname=0.0.0.0", \
                   "-Dcom.sun.management.jmxremote.local.only=false", \
                   "-Djava.rmi.server.port=1099", \
                   "-Xms512m", "-Xmx512m", \
                   "-jar", "/app/myapp.jar"]